[meta]
name = "Cave E: Guards"
time_limit = 150
diamonds_required = 4
diamond_value = 50
bonus_diamond_value = 90

[colors]
background1 = "lightred"
background2 = "brown"
foreground = "white"

[level]
data = """
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
WX.....................................W
W......................................W
W......................................W
W......................................W
W......................................W
W......................................W
W......................................W
W.......  q.....  q.....  q.....  q....W
W.......   .....   .....   .....   ....W
W....... d ..... d ..... d ..... d ....W
W......................................W
W......................................W
W......................................W
W.......  q.....  q.....  q.....  q....W
W.......   .....   .....   .....   ....W
W....... d ..... d ..... d ..... d ....W
W......................................W
W......................................W
W......................................W
W......................................P
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
"""

