[meta]
name = "Cave N: Zigzag"
time_limit = 150
diamonds_required = 30
diamond_value = 10
bonus_diamond_value = 20

[colors]
background1 = "orange"
background2 = "gray2"
foreground = "white"

[level]
data = """
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
W..X...................................W
W......................................W
W......................................W
W......................................W
W.....................q.q.q.q.q.q......W
W.....................r.r.r.r.r.r......W
W......................................W
W......................................W
W..........B. . . . . .................W
W.......... . . . . . .................W
W.......... .B. . . . .................W
W.......... . . . . . .................W
W.......... . .B. . . .................W
W.......... . . . . . .................W
W.......... . . .B. . .................W
W.......... . . . . . .................W
W.......... . . . .B. .................W
W.......... . . . . . .................P
W.......... . . . . .B.................W
W......................................W
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
"""

