[meta]
name = "Intermission 1"
time_limit = 30
diamonds_required = 6
diamond_value = 30
bonus_diamond_value = 0

[colors]
background1 = "lightred"
background2 = "lightblue"
foreground = "white"

[level]
data = """
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
W                   WWWWWWWWWWWWWWWWWWWW
W         r         WWWWWWWWWWWWWWWWWWWW
W  X      .         WWWWWWWWWWWWWWWWWWWW
W                   WWWWWWWWWWWWWWWWWWWW
W                   WWWWWWWWWWWWWWWWWWWW
W                   WWWWWWWWWWWWWWWWWWWW
W                   WWWWWWWWWWWWWWWWWWWW
W                   WWWWWWWWWWWWWWWWWWWW
W                   WWWWWWWWWWWWWWWWWWWW
W         B       P WWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
"""

