[meta]
name = "Intermission 3"
time_limit = 20
diamonds_required = 14
diamond_value = 10
bonus_diamond_value = 0

[colors]
background1 = "orange"
background2 = "blue"
foreground = "white"

[level]
data = """
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
W       X          WWWWWWWWWWWWWWWWWWWWW
W                  WWWWWWWWWWWWWWWWWWWWW
W                  WWWWWWWWWWWWWWWWWWWWW
W                  WWWWWWWWWWWWWWWWWWWWW
W                 PWWWWWWWWWWWWWWWWWWWWW
W                  WWWWWWWWWWWWWWWWWWWWW
W              qqqqWWWWWWWWWWWWWWWWWWWWW
W              qqqqWWWWWWWWWWWWWWWWWWWWW
W              qqqqWWWWWWWWWWWWWWWWWWWWW
WddddddddddddddqqqqWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
"""

