[meta]
name = "Intermission 2"
time_limit = 15
diamonds_required = 16
diamond_value = 10
bonus_diamond_value = 0

[colors]
background1 = "lightgray"
background2 = "blue"
foreground = "white"

[level]
data = """
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
Wrq...............r.WWWWWWWWWWWWWWWWWWWW
WXrq.............rP.WWWWWWWWWWWWWWWWWWWW
Wd.rq...........r.d.WWWWWWWWWWWWWWWWWWWW
Wrd.rq.........r.dr.WWWWWWWWWWWWWWWWWWWW
W.rd.rq.......r.dr..WWWWWWWWWWWWWWWWWWWW
W..rd.rq.....r.dr...WWWWWWWWWWWWWWWWWWWW
W...rd.rq...r.dr....WWWWWWWWWWWWWWWWWWWW
W....rd.rq.r.dr.....WWWWWWWWWWWWWWWWWWWW
W.....rd.rr.dr......WWWWWWWWWWWWWWWWWWWW
W......rd..dr.......WWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
"""

